Pac update
psoc-rs/psoc6-pac pull request #4
Opened 2022-10-22 00:41 UTC by diagonalDave

This PR has regenerated the PAC, provided a generate.bat and gated interrupts for the CM0+ core.

2022-10-24 18:12 UTC, mvertescher requested changes
Thanks for posting this update @diagonalDave! Looks pretty good to me, just a few minor comments.

2022-10-24 18:12 UTC, mvertescher commented on Cargo.toml
> +repository = "https://github.com/diagonalDave/psoc6-pac.git"
We can probably just point at `https://github.com/psoc-rs/psoc6-pac` here and use the `psoc-rs` org link for other spots too.

2022-10-24 18:12 UTC, mvertescher commented on README.md
> +psoc6-pac = "0.1.1"
This should be `0.0.1` right?

2022-10-26 20:59 UTC, diagonalDave commented
Yep.

On Tue, Oct 25, 2022 at 5:12 AM Matt Vertescher ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for posting this update @diagonalDave
> <https://github.com/diagonalDave>! Looks pretty good to me, just a few
> minor comments.
> ------------------------------
>
> In Cargo.toml
> <https://github.com/psoc-rs/psoc6-pac/pull/4#discussion_r1003603843>:
>
> >  edition = "2018"
>  description = "Peripheral Access Crate for Cypress PSoC 6 MCUs"
>  documentation = "https://docs.rs/psoc6-pac/"
> -repository = "https://github.com/jonas-schievink/psoc6-pac.git"
> +repository = "https://github.com/diagonalDave/psoc6-pac.git"
>
> We can probably just point at https://github.com/psoc-rs/psoc6-pac here
> and use the psoc-rs org link for other spots too.
> ------------------------------
>
> In README.md
> <https://github.com/psoc-rs/psoc6-pac/pull/4#discussion_r1003608630>:
>
> > @@ -18,11 +18,14 @@ Add an entry to your `Cargo.toml`:
>
>  ```toml
>  [dependencies]
> -psoc6-pac = "0.0.0"
> +psoc6-pac = "0.1.1"
>
> This should be 0.0.1 right?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/psoc-rs/psoc6-pac/pull/4#pullrequestreview-1153558905>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2GTI7UESSMF7AJHZIV6TLWE3GSVANCNFSM6AAAAAARLTRURM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-11 02:13 UTC, diagonalDave commented on Cargo.toml
> +repository = "https://github.com/diagonalDave/psoc6-pac.git"
Hopefully resolved both issues in latest commit.

2022-11-18 19:24 UTC, mvertescher commented
Thanks for the changes @diagonalDave LGTM!

2022-11-18 19:24 UTC, merged